import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { validUuid } from "@/lib/admin/http";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string; mediaId: string }> }) {
  try { const { id, mediaId } = await params; if (!validUuid(id) || !validUuid(mediaId)) throw new Error("Invalid ID"); const db = createSupabaseAdminClient(); const { data, error } = await db.from("media_assets").select("storage_path").eq("id", mediaId).eq("venue_id", id).single(); if (error) throw error; const { error: storageError } = await db.storage.from("exhibition-images").remove([data.storage_path]); if (storageError) throw storageError; const { error: deleteError } = await db.from("media_assets").delete().eq("id", mediaId).eq("venue_id", id); if (deleteError) throw deleteError; const [{ data: approved }, { data: sources }] = await Promise.all([db.from("media_assets").select("id").eq("venue_id", id).eq("rights_status", "approved"), db.from("source_records").select("id").eq("venue_id", id)]); let imageSearchStatus = approved?.length ? "approved_image_exists" : "no_image_candidate"; if (!approved?.length && sources?.length) { const { data: candidates } = await db.from("source_image_candidates").select("review_status,is_active").in("source_record_id", sources.map((source) => source.id)); const active = (candidates || []).filter((candidate) => candidate.is_active); imageSearchStatus = active.some((candidate) => candidate.review_status === "accepted") ? "image_candidate_kept" : active.some((candidate) => candidate.review_status === "unreviewed") ? "image_candidate_found" : active.length ? "image_candidate_rejected" : "no_image_candidate"; } await db.from("venues").update({ image_search_status: imageSearchStatus }).eq("id", id); revalidatePath("/admin/venues"); revalidatePath(`/admin/venues/${id}`); return NextResponse.json({ message: "Venue画像を削除しました。", removedAssetId: mediaId }); }
  catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Delete failed" }, { status: 400 }); }
}
