import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { slugify } from "@/lib/admin/slug";
import { calculateCompleteness } from "@/lib/admin/master-completeness";
import { shouldApplySourceField } from "@/lib/venue-enrichment/source-application";
import { discoverArtistSample, discoverWikidataArtists } from "./artist-discovery";
import { fetchNormalizedArtists } from "./artist-mapper";
import { saveArtistImageDiscovery } from "./artist-image-discovery";
import type { ArtistImportCoverage, WikidataArtist, WikidataArtistImportSummary } from "./artist-types";

const SOURCE = "wikidata"; const PAGE_SIZE = 100;
type Existing = Record<string, unknown> & { id: string; name: string; name_en?: string | null; aliases?: string[]; birth_year?: number | null; publication_status?: string };
function normalized(value: string) { return value.normalize("NFKC").toLowerCase().replace(/[\s・._-]+/g, ""); }
function names(row: Existing) { return [row.name, row.name_en || "", ...(row.aliases || [])].filter(Boolean).map(normalized); }

export function scoreArtistMatch(row: Existing, artist: WikidataArtist) {
  const incoming = [artist.name, artist.nameEn || "", ...artist.aliases].filter(Boolean).map(normalized); const current = names(row);
  const exact = incoming.some((value) => current.includes(value)); let score = exact ? 0.82 : 0; const reasons: string[] = exact ? ["exact name/alias"] : [];
  if (exact && row.birth_year != null && artist.birthYear != null) { if (Number(row.birth_year) === artist.birthYear) { score += 0.18; reasons.push("birth year"); } else { score -= 0.45; reasons.push("birth year conflict"); } }
  return { confidence: Math.max(0, Math.min(1, score)), reasons };
}

export function shouldSkipArtistSource(prior: { checksum?: string | null; artist_id?: string | null } | null, checksum: string) { return Boolean(prior?.artist_id && prior.checksum === checksum); }
function envelope(artist: WikidataArtist) { return { qid: artist.qid, normalized: artist, classification: { occupation: artist.occupation, field_of_work: artist.fieldOfWork, movement: artist.movement, nationality_qids: artist.nationalityQids }, raw: artist.raw }; }
function fields(artist: WikidataArtist) { return { name: artist.name, name_en: artist.nameEn, name_native: artist.nameNative, aliases: artist.aliases, birth_date: artist.birthDate, birth_year: artist.birthYear, death_date: artist.deathDate, death_year: artist.deathYear, nationality_country_code: artist.nationalityCountryCode, birth_country_code: artist.birthCountryCode, birth_place: artist.birthPlace, official_url: artist.officialUrl }; }

async function allArtists(db: SupabaseClient) { const rows: Existing[] = []; for (let offset = 0;; offset += 1000) { const { data, error } = await db.from("artists").select("*").range(offset, offset + 999); if (error) throw error; rows.push(...((data || []) as Existing[])); if ((data || []).length < 1000) break; } return rows; }
async function sourceIds(db: SupabaseClient) { const { data, error } = await db.from("data_sources").select("id,key").in("key", ["wikidata", "wikimedia_commons"]); if (error) throw error; return Object.fromEntries((data || []).map((row) => [row.key, row.id])) as Record<string, string>; }
async function provenance(db: SupabaseClient, artistId: string) { const { data, error } = await db.from("artist_field_sources").select("field_name,source").eq("artist_id", artistId).eq("is_current", true); if (error) throw error; return new Map((data || []).map((row) => [row.field_name, row.source])); }
async function saveProvenance(db: SupabaseClient, artistId: string, field: string, value: unknown, sourceRecordId: string, qid: string, current: boolean) {
  if (current) await db.from("artist_field_sources").update({ is_current: false }).eq("artist_id", artistId).eq("field_name", field).eq("is_current", true);
  const { data: same } = await db.from("artist_field_sources").select("id").eq("artist_id", artistId).eq("field_name", field).eq("source_record_id", sourceRecordId).eq("value_snapshot", value).maybeSingle();
  if (same) { await db.from("artist_field_sources").update({ is_current: current, review_status: current ? "applied" : "unreviewed", updated_at: new Date().toISOString() }).eq("id", same.id); return; }
  const { error } = await db.from("artist_field_sources").insert({ artist_id: artistId, field_name: field, source: SOURCE, source_url: `https://www.wikidata.org/wiki/${qid}`, source_record_id: sourceRecordId, value_snapshot: value, generated_by_ai: false, review_status: current ? "applied" : "unreviewed", is_current: current }); if (error) throw error;
}
async function upsertSource(db: SupabaseClient, sourceId: string, artist: WikidataArtist) { const payload = envelope(artist); const checksum = createHash("sha256").update(JSON.stringify(payload)).digest("hex"); const { data: prior } = await db.from("source_records").select("id,artist_id,checksum").eq("data_source_id", sourceId).eq("external_id", artist.qid).maybeSingle(); const { data, error } = await db.from("source_records").upsert({ data_source_id: sourceId, external_id: artist.qid, artist_id: prior?.artist_id || null, source_url: `https://www.wikidata.org/wiki/${artist.qid}`, raw_payload: payload, checksum, fetched_at: new Date().toISOString() }, { onConflict: "data_source_id,external_id" }).select("id,artist_id,checksum").single(); if (error || !data) throw error || new Error("Source record save failed"); return { prior, record: data, checksum }; }
async function createArtist(db: SupabaseClient, artist: WikidataArtist) { const { data, error } = await db.from("artists").insert({ ...fields(artist), slug: `${slugify(artist.name)}-${artist.qid.toLowerCase()}`, publication_status: "draft" }).select("*").single(); if (error || !data) throw error || new Error("Artist creation failed"); return data as Existing; }
async function applyArtist(db: SupabaseClient, target: Existing, artist: WikidataArtist, sourceRecordId: string) { const sources = await provenance(db, target.id); const updates: Record<string, unknown> = {}; for (const [field, value] of Object.entries(fields(artist))) { if (value == null || (Array.isArray(value) && !value.length)) continue; const current = shouldApplySourceField(target[field], sources.get(field), SOURCE); if (current) updates[field] = value; if (current || JSON.stringify(target[field]) !== JSON.stringify(value)) await saveProvenance(db, target.id, field, value, sourceRecordId, artist.qid, current); } if (Object.keys(updates).length) { const { error } = await db.from("artists").update(updates).eq("id", target.id); if (error) throw error; } return Object.keys(updates).length > 0; }

async function saveAmbiguous(db: SupabaseClient, candidates: Existing[], artist: WikidataArtist) { for (const target of candidates) { const match = scoreArtistMatch(target, artist); await db.from("artist_external_match_candidates").upsert({ artist_id: target.id, provider: SOURCE, external_id: artist.qid, label_ja: artist.name, label_en: artist.nameEn, birth_year: artist.birthYear, confidence: match.confidence, match_reasons: match.reasons, raw_payload: envelope(artist), last_seen_at: new Date().toISOString() }, { onConflict: "artist_id,provider,external_id" }); } }

function metric(row: Record<string, unknown>, key: string) { const assets = (row.media_assets || []) as Array<Record<string, unknown>>; const sources = (row.source_records || []) as Array<Record<string, unknown>>; const source = sources.find((item) => item.external_id && /^Q\d+$/.test(String(item.external_id))); const normalizedArtist = (source?.raw_payload as { normalized?: WikidataArtist } | undefined)?.normalized; switch (key) { case "name": return Boolean(row.name); case "nameEn": return Boolean(row.name_en); case "nationality": return Boolean(row.nationality_country_code); case "p18": return Boolean(normalizedArtist?.imageFileTitle); case "imageCandidate": return sources.some((item) => ((item.source_image_candidates || []) as unknown[]).length); case "primaryImage": return assets.some((item) => item.is_primary); case "aliases": return Boolean((row.aliases as unknown[] | undefined)?.length); case "birth": return Boolean(row.birth_date || row.birth_year); case "death": return Boolean(row.death_date || row.death_year); case "birthPlace": return Boolean(row.birth_place); case "occupation": return Boolean(normalizedArtist?.occupation.length); case "fieldOfWork": return Boolean(normalizedArtist?.fieldOfWork.length); case "movement": return Boolean(normalizedArtist?.movement.length); case "wikipedia": return Boolean(normalizedArtist?.wikipediaArticleTitle); default: return false; } }
export function artistCoverage(rows: Record<string, unknown>[]) { const keys = ["name", "nameEn", "nationality", "p18", "imageCandidate", "primaryImage", "aliases", "birth", "death", "birthPlace", "occupation", "fieldOfWork", "movement", "wikipedia"]; const coverage = Object.fromEntries(keys.map((key) => { const filled = rows.filter((row) => metric(row, key)).length; return [key, { filled, missing: rows.length - filled, percent: rows.length ? Math.round(filled / rows.length * 100) : 0 }]; })) as ArtistImportCoverage; return coverage; }

export async function importWikidataArtists(input: { mode: "count" | "full"; count?: number; offset?: number; qids?: string[] }, db: SupabaseClient = createSupabaseAdminClient()): Promise<WikidataArtistImportSummary> {
  const targetedQids = [...new Set((input.qids || []).filter((value) => /^Q\d+$/.test(value)))].slice(0, 100);
  const ids = await sourceIds(db); const count = targetedQids.length || Math.max(1, Math.min(500, Math.floor(input.count || 20))); const { data: run, error: runError } = await db.from("import_runs").insert({ data_source_id: ids.wikidata, operation_type: targetedQids.length ? "wikidata_artist_targeted_import" : "wikidata_artist_import", status: "running", requested_count: input.mode === "count" ? count : 0, metrics: { mode: input.mode, targeted: Boolean(targetedQids.length) } }).select("id").single(); if (runError || !run) throw runError || new Error("Import run creation failed");
  const result: WikidataArtistImportSummary = { runId: run.id, mode: input.mode, requested: input.mode === "count" ? count : null, discovered: 0, fetched: 0, processed: 0, newArtists: 0, linkedExisting: 0, updated: 0, unchanged: 0, sourceSelectionRequired: 0, imageCandidatesAdded: 0, errors: [], coverage: {}, imageCoverage: { wikidataP18: 0, commonsCategory: 0, wikipediaArticle: 0, candidate: 0, primary: 0, rightsNeedsReview: 0, rightsApproved: 0 }, averageCompleteness: 0, coreComplete: 0 };
  const existing = await allArtists(db); const touched = new Set<string>();
  const process = async (discovered: Array<{ qid: string }>) => { result.discovered += discovered.length; const fetched = await fetchNormalizedArtists(discovered); result.fetched += fetched.artists.length; result.errors.push(...fetched.errors); for (const artist of fetched.artists) { result.processed += 1; try { const source = await upsertSource(db, ids.wikidata, artist); if (shouldSkipArtistSource(source.prior, source.checksum)) { result.unchanged += 1; if (source.prior?.artist_id) { touched.add(source.prior.artist_id); const images = await saveArtistImageDiscovery(db, source.prior.artist_id, artist); result.imageCandidatesAdded += images.added; } continue; } let target = source.prior?.artist_id ? existing.find((row) => row.id === source.prior!.artist_id) : null; if (!target) { const scored = existing.map((row) => ({ row, ...scoreArtistMatch(row, artist) })).filter((item) => item.confidence >= 0.8).sort((a, b) => b.confidence - a.confidence); if (scored.length > 1 && scored[0].confidence === scored[1].confidence) { await saveAmbiguous(db, scored.map((item) => item.row), artist); result.sourceSelectionRequired += 1; continue; } if (scored.length === 1) { target = scored[0].row; result.linkedExisting += 1; } else { target = await createArtist(db, artist); existing.push(target); result.newArtists += 1; } }
      await db.from("source_records").update({ artist_id: target.id }).eq("id", source.record.id); const changed = await applyArtist(db, target, artist, source.record.id); if (changed && source.prior?.artist_id) result.updated += 1; touched.add(target.id); const images = await saveArtistImageDiscovery(db, target.id, artist); result.imageCandidatesAdded += images.added;
    } catch (error) { result.errors.push({ qid: artist.qid, message: error instanceof Error ? error.message : "Artist import failed" }); } } };
  try { if (targetedQids.length) await process(targetedQids.map((qid) => ({ qid }))); else if (input.mode === "count") await process(await discoverArtistSample(count, Math.max(0, Math.floor(input.offset || 0)))); else { let cursor: string | null = null; for (;;) { const page = await discoverWikidataArtists({ limit: PAGE_SIZE, afterQid: cursor }); await process(page); const nextCursor: string | null = page.at(-1)?.qid || cursor; if (page.length < PAGE_SIZE) break; if (nextCursor === cursor) throw new Error("Artist discovery cursor did not advance"); cursor = nextCursor; } }
    const { data: rows } = touched.size ? await db.from("artists").select("*,media_assets(*),source_records!source_records_artist_id_fkey(*,source_image_candidates(*))").in("id", [...touched]) : { data: [] };
    const records = (rows || []) as Record<string, unknown>[];
    const artistCandidates = (row: Record<string, unknown>) => ((row.source_records || []) as Array<Record<string, unknown>>).flatMap((source) => (source.source_image_candidates || []) as Array<Record<string, unknown>>);
    result.coverage = artistCoverage(records);
    result.averageCompleteness = records.length ? Math.round(records.reduce((sum, row) => sum + calculateCompleteness("artists", row).percent, 0) / records.length) : 0;
    result.coreComplete = records.filter((row) => metric(row, "name") && metric(row, "nationality") && metric(row, "primaryImage")).length;
    result.imageCoverage = {
      wikidataP18: records.filter((row) => artistCandidates(row).some((item) => item.discovery_source === "wikidata_p18")).length,
      commonsCategory: records.filter((row) => artistCandidates(row).some((item) => item.discovery_source === "commons_category")).length,
      wikipediaArticle: records.filter((row) => artistCandidates(row).some((item) => item.discovery_source === "wikipedia_article")).length,
      candidate: result.coverage.imageCandidate?.filled || 0,
      primary: result.coverage.primaryImage?.filled || 0,
      rightsNeedsReview: records.filter((row) => ((row.media_assets || []) as Array<Record<string, unknown>>).some((item) => item.is_primary && item.rights_status === "needs_review")).length,
      rightsApproved: records.filter((row) => ((row.media_assets || []) as Array<Record<string, unknown>>).some((item) => item.is_primary && item.rights_status === "approved")).length,
    };
    await db.from("import_runs").update({ status: result.errors.length ? "partial" : "completed", fetched_count: result.fetched, created_count: result.newArtists, updated_count: result.updated + result.linkedExisting, skipped_count: result.unchanged, error_count: result.errors.length, errors: result.errors.length ? result.errors : null, metrics: result, finished_at: new Date().toISOString() }).eq("id", run.id); return result;
  } catch (error) { result.errors.push({ message: error instanceof Error ? error.message : "Artist import failed" }); await db.from("import_runs").update({ status: "failed", error_count: result.errors.length, errors: result.errors, metrics: result, finished_at: new Date().toISOString() }).eq("id", run.id); return result; }
}
