export type VenueRow = {
  id: string;
  slug: string;
  name: string;
  name_en: string | null;
  name_native: string | null;
  aliases: string[];
  venue_type: string;
  postal_code: string | null;
  prefecture: string | null;
  city: string | null;
  address: string | null;
  country_code: string | null;
  region: string | null;
  district: string | null;
  description: string | null;
  access_text: string | null;
  opening_hours_text: string | null;
  closed_days_text: string | null;
  opening_note: string | null;
  publication_status: "draft" | "ready" | "published" | "archived";
  is_active: boolean;
  official_url: string | null;
  inception_year: number | null;
  latitude: number | null;
  longitude: number | null;
  wikidata_match_status: string;
  wikidata_match_confidence: number | null;
  wikidata_match_reason: string | null;
  best_wikidata_candidate_qid: string | null;
  coordinate_source: string | null;
  coordinate_precision: string | null;
  coordinate_status: "missing" | "candidate" | "approved" | "manual" | "rejected";
  coordinate_candidate_qid: string | null;
  coordinate_candidate_latitude: number | null;
  coordinate_candidate_longitude: number | null;
  coordinate_candidate_source: "wikidata" | "geolonia" | null;
  coordinate_candidate_confidence: number | null;
  coordinate_candidate_threshold: number | null;
  coordinate_candidate_reason: string | null;
  coordinate_candidate_distance_m: number | null;
  coordinate_candidate_decided_at: string | null;
  geolonia_candidate_latitude: number | null;
  geolonia_candidate_longitude: number | null;
  geolonia_candidate_precision: string | null;
  coordinate_search_trace: Array<Record<string, unknown>>;
  image_search_status: "no_entity_candidate" | "no_image_candidate" | "image_candidate_found" | "image_candidate_kept" | "image_candidate_rejected" | "approved_image_exists" | "qid_missing" | "no_image_found" | "p18_found" | "commons_candidate_found" | "wikipedia_candidate_found";
  image_candidate_found_threshold: number | null;
  image_candidate_found_confidence: number | null;
  image_candidate_found_qid: string | null;
  image_candidate_found_reason: string | null;
  image_search_trace: Array<Record<string, unknown>>;
  enriched_at: string | null;
  updated_at: string;
  exhibition_occurrences?: Array<OccurrenceRow & { exhibitions?: ExhibitionRow | ExhibitionRow[] | null }>;
  media_assets?: MediaAssetRow[];
  source_records?: SourceRecordRow[];
  venue_external_match_candidates?: VenueMatchCandidateRow[];
  official_venue_crawl_results?: OfficialVenueCrawlResultRow[];
  venue_field_sources?: VenueFieldSourceRow[];
};

export type VenueFieldSourceRow = {
  id: string;
  field_name: string;
  source: string;
  source_url: string | null;
  generated_by_ai: boolean;
  ai_confidence: "high" | "medium" | "low" | null;
  transformation_notes: string | null;
  review_status: string;
  is_current: boolean;
  created_at: string;
  source_record_id?: string | null;
};

export type OfficialVenueCrawlResultRow = {
  id: string;
  crawl_status: string;
  crawled_at: string;
  crawl_source_url: string | null;
  discovered_urls: string[];
  extracted_values: Record<string, unknown>;
  field_source_urls: Record<string, string>;
  description_source_text: string | null;
  official_source_text: string | null;
  description_source_url: string | null;
  phone: string | null;
  ambiguous_fields: Record<string, unknown>;
  notes: string | null;
};

export type OccurrenceRow = {
  id: string;
  exhibition_id: string;
  venue_id: string;
  start_date: string | null;
  end_date: string | null;
  opening_hours_text: string | null;
  closed_days_text: string | null;
  ticket_url: string | null;
  venues?: VenueRow | VenueRow[] | null;
};

export type ExhibitionRelationDiagnostic = { id: string; match_status?: string; resolution_status?: string; last_seen_at?: string | null; relation_status?: string };

export type MediaAssetRow = {
  id: string;
  exhibition_id: string | null;
  venue_id: string | null;
  artist_id: string | null;
  work_id: string | null;
  kind: string;
  storage_path: string;
  original_filename: string | null;
  source_type: string | null;
  source_url: string | null;
  credit: string | null;
  usage_note: string | null;
  reported_license: string | null;
  reported_license_url: string | null;
  reported_author: string | null;
  reported_usage_terms: string | null;
  rights_status: string;
  rights_checked_at: string | null;
  valid_until: string | null;
  is_primary: boolean;
  created_at: string;
  signedUrl?: string | null;
};

export type SourceRecordRow = {
  id: string;
  external_id: string;
  source_url: string | null;
  fetched_at: string;
  last_seen_at?: string | null;
  last_changed_at?: string | null;
  raw_payload: unknown;
  exhibition_id?: string | null;
  venue_id?: string | null;
  artist_id?: string | null;
  work_id?: string | null;
  data_sources?: { name: string; key: string } | { name: string; key: string }[] | null;
  source_image_candidates?: SourceImageCandidateRow[];
};

export type SourceImageCandidateRow = {
  id: string;
  image_url: string;
  thumbnail_url: string | null;
  provider: string | null;
  stable_identifier: string | null;
  source_url: string | null;
  author: string | null;
  credit: string | null;
  license_short_name: string | null;
  license_url: string | null;
  usage_terms: string | null;
  rights_status: "rejected" | "needs_review" | "approved";
  candidate_entity_id: string | null;
  candidate_entity_label: string | null;
  candidate_match_confidence: number | null;
  candidate_match_threshold: number | null;
  candidate_kind: string;
  discovery_source: "wikidata_p18" | "commons_category" | "wikipedia_article" | "artist_official" | "gallery_official" | "foundation_estate" | "museum_official" | "official_press" | "open_collection" | null;
  source_type?: string | null;
  commercial_use?: "allowed" | "forbidden" | "unknown" | null;
  modification_crop?: "allowed" | "forbidden" | "unknown" | null;
  attribution_requirement?: "required" | "not_required" | "unknown" | null;
  valid_until?: string | null;
  notes?: string | null;
  contents_rights_type: string | null;
  contents_access: string | null;
  review_status: string;
  is_active: boolean;
};

export type VenueMatchCandidateRow = {
  id: string;
  external_id: string;
  label_ja: string | null;
  label_en: string | null;
  description: string | null;
  official_url: string | null;
  latitude: number | null;
  longitude: number | null;
  image_file_title: string | null;
  confidence: number;
  match_reasons: string[];
  status: string;
  raw_payload?: unknown;
};

export type ExhibitionRow = {
  id: string;
  slug: string;
  title: string;
  title_en: string | null;
  description: string | null;
  exhibition_type: string | null;
  official_url: string | null;
  publication_status: string;
  updated_at: string;
  exhibition_occurrences?: OccurrenceRow[];
  exhibition_artists?: ExhibitionRelationDiagnostic[];
  exhibition_artist_mentions?: ExhibitionRelationDiagnostic[];
  exhibition_venue_mentions?: ExhibitionRelationDiagnostic[];
  media_assets?: MediaAssetRow[];
  source_records?: SourceRecordRow[];
};
